// <auto-generated />
using System;
using APIFarmacia.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIFarmacia.Migrations
{
    [DbContext(typeof(ConexionPostgreSQL))]
    partial class ConexionPostgreSQLModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIFarmacia.Models.Cliente", b =>
                {
                    b.Property<int>("cli_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cli_id"));

                    b.Property<string>("cli_apellidos")
                        .HasColumnType("text");

                    b.Property<string>("cli_cedula")
                        .HasColumnType("text");

                    b.Property<string>("cli_correo")
                        .HasColumnType("text");

                    b.Property<string>("cli_direccion")
                        .HasColumnType("text");

                    b.Property<string>("cli_nombres")
                        .HasColumnType("text");

                    b.Property<string>("cli_telefono")
                        .HasColumnType("text");

                    b.Property<int?>("type_Person")
                        .HasColumnType("integer");

                    b.HasKey("cli_id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("APIFarmacia.Models.Detalle_Factura", b =>
                {
                    b.Property<int>("det_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("det_id"));

                    b.Property<int>("det_cantidad")
                        .HasColumnType("integer");

                    b.Property<double>("det_iva")
                        .HasColumnType("double precision");

                    b.Property<double>("det_precio_unitario")
                        .HasColumnType("double precision");

                    b.Property<double>("det_subtotal")
                        .HasColumnType("double precision");

                    b.Property<double>("det_total")
                        .HasColumnType("double precision");

                    b.Property<int>("factura_id")
                        .HasColumnType("integer");

                    b.Property<int>("producto_id")
                        .HasColumnType("integer");

                    b.HasKey("det_id");

                    b.ToTable("Detalle_Facturas");
                });

            modelBuilder.Entity("APIFarmacia.Models.Factura", b =>
                {
                    b.Property<int>("fac_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("fac_id"));

                    b.Property<string>("fac_fecha")
                        .HasColumnType("text");

                    b.Property<int?>("fac_numero")
                        .HasColumnType("integer");

                    b.Property<double?>("fac_subtotal")
                        .HasColumnType("double precision");

                    b.Property<int?>("fac_tipo")
                        .HasColumnType("integer");

                    b.Property<double?>("fac_total")
                        .HasColumnType("double precision");

                    b.Property<double?>("fac_total_iva")
                        .HasColumnType("double precision");

                    b.Property<int?>("id_cliente")
                        .HasColumnType("integer");

                    b.Property<int?>("id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("fac_id");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("APIFarmacia.Models.Productos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("codigo_producto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("iva")
                        .HasColumnType("double precision");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("precio")
                        .HasColumnType("double precision");

                    b.Property<double>("stock")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("APIFarmacia.Models.Usuarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fechanacimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("passwords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("permisos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
